language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
env:
  global:
    secure: fgoG2mJSTIMEkOmEVwFIjQcwBuw2Wpu7DrVG0KFKXuLcubCZopFDJdK1MeH1faR2N8zPwRcQnQIGRZ/jD8cG68Ofnh+7B4NX2gLJIQs62kDeNlNdGvcr4IFww/jwm1UxqW/+3NYJvKmr1+VQkcHnd/LFZpUxMSzVpRLB7GIWyfFUF+lvaY9kSaA30zrpkb2r84yd76oHJz4mHI5OCJBD/VZwb+GP7nel6hK3pOUcXRYcCY7ooY9lcB3/QTt6debdJbhfCcKv1P38xpRAHgZKac43llF8uv2J+y2Qu6MaPlzkdUs+XCnSxwSgTyoLyZ2djLyNpqW1Yd0MOvAX/hduAel78Xfl+clBmOB5JpQjoM0IwGkQvBnxw2zchicUUaDheLkfVQdCxb0VwvdCjw7JbcbH3fIga8NtB3m13JGTi7ttKxrWHH5KOHurQch/yOzbS/8omm3eSg99vomcZ53WbRu69IiuZ0IQ5egrJBl6o892OaVBOPiLpF5+fcTtNyr1plaxMGPQE4jOfnVND72g6GMOJjYdpihfa5GISDcyT2byslTXJg0/mexu3lmqhOaIE3M/TW1jeJAgUDUPZp+Ns3vz0a2bHV/022dnrLJ+v0LYxWHAyeoJI4MxfE7yulfl89FEACrn4Y3/l09NdHr60CnpKCZ4QCN1J27bVMsw4Kg=
deploy:
  api_key:
    secure: BfGRuMiA/XoWK2NTD+BhVoOJe57rZR9ifDcVWZxWaNv4v7UJgLsZVWcK0DPJ5f3Rek4+m0fAtD8KH3NeryePA0KXvy3QQyxQto/rZRwBmlAk7FcVDokqX1HibJ+JyJcb06zeyNjd5AHOFX5+SaynitpO4IzWFsUPK7E7XbT7aiU9HdVl6i1GvQSq1X+24OF8mryrDDqauvV/VdCANwRgQ7cMnfNrueaX/CxbuZpJEV9Ffo3c+94VroItip5LE0n6GiU57Mb0ZT7xB7bphl7Ymy4dS0EdtWHFJckxMXX/dW/GlJO2KAMPBdwnSbUTnB5EJf4l/DoNZTfbX0owxFV93OLSshPigliKvjr9icJPw9dG41LTXGunwDVY5e27Pf5Kc6B0+x5z+OG6shj/NjrEcTZZQl2xqpDmbkyyKcliOQN0ZYV2zzm4+ZhQBCMvoFhFmBY1eUL6hHZJqZkMY/nrKiMz42HWoJ8LBDzkUZGGteprmXF3qhYtRw9Fi1MDQX1kEumQ9se97PaC//4Ctwt3DUsxCXHWBxL28PXmdaN373TwJlZDPr9/H+QpyAqs1jy4NqEKsuBc7ZJGduYeNvHJ7JZ/Yco2bykPrn3WrhajNJA3YDboE2+JURPZbwh9Ko1ZIpg9ibFX08OTQZ88hJt7L55zBpRDJK6VsDUVvl7Z5UI=
services:
    - postgresql
